import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // CERAMIC PRODUCTS (IDs 1-30)
        {
            name: 'Product 1',
            price: 320,
            image: 'ceramic1.jpg',
            category: 'ceramic-products',
            description: 'Traditional handcrafted ceramic bowl featuring intricate blue and white patterns inspired by ancient pottery techniques.',
            artisanId: 3,
            createdAt: new Date('2024-02-15').toISOString(),
        },
        {
            name: 'Product 2',
            price: 450,
            image: 'ceramic2.jpg',
            category: 'ceramic-products',
            description: 'Elegant ceramic vase with hand-painted floral motifs, showcasing the artisan\'s mastery in glazing techniques.',
            artisanId: 7,
            createdAt: new Date('2024-03-10').toISOString(),
        },
        {
            name: 'Product 3',
            price: 580,
            image: 'ceramic3.jpg',
            category: 'ceramic-products',
            description: 'Handmade ceramic dinner plate set with earthy tones and rustic finish, perfect for everyday dining.',
            artisanId: 2,
            createdAt: new Date('2024-01-25').toISOString(),
        },
        {
            name: 'Product 4',
            price: 720,
            image: 'ceramic4.jpg',
            category: 'ceramic-products',
            description: 'Premium ceramic teapot crafted with precision, featuring traditional geometric patterns and durable glaze.',
            artisanId: 5,
            createdAt: new Date('2024-04-05').toISOString(),
        },
        {
            name: 'Product 5',
            price: 390,
            image: 'ceramic5.jpg',
            category: 'ceramic-products',
            description: 'Decorative ceramic tiles with vibrant colors and intricate mandala designs, handcrafted by skilled artisans.',
            artisanId: 9,
            createdAt: new Date('2024-02-28').toISOString(),
        },
        {
            name: 'Product 6',
            price: 650,
            image: 'ceramic6.jpg',
            category: 'ceramic-products',
            description: 'Artistic ceramic sculpture featuring contemporary design with traditional glazing methods passed down through generations.',
            artisanId: 1,
            createdAt: new Date('2024-03-20').toISOString(),
        },
        {
            name: 'Product 7',
            price: 480,
            image: 'ceramic7.jpg',
            category: 'ceramic-products',
            description: 'Handcrafted ceramic mug set with unique texture and natural clay finish, perfect for morning coffee rituals.',
            artisanId: 4,
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'Product 8',
            price: 820,
            image: 'ceramic8.jpg',
            category: 'ceramic-products',
            description: 'Exquisite ceramic serving platter with hand-painted traditional motifs, ideal for special occasions.',
            artisanId: 8,
            createdAt: new Date('2024-04-12').toISOString(),
        },
        {
            name: 'Product 9',
            price: 370,
            image: 'ceramic9.jpg',
            category: 'ceramic-products',
            description: 'Classic ceramic bowl with smooth glazed finish and timeless design, showcasing authentic craftsmanship.',
            artisanId: 6,
            createdAt: new Date('2024-02-08').toISOString(),
        },
        {
            name: 'Product 10',
            price: 550,
            image: 'ceramic10.jpg',
            category: 'ceramic-products',
            description: 'Artisanal ceramic jar with lid, featuring hand-carved patterns and multi-layered glazing technique.',
            artisanId: 10,
            createdAt: new Date('2024-03-15').toISOString(),
        },
        {
            name: 'Product 11',
            price: 680,
            image: 'ceramic11.jpg',
            category: 'ceramic-products',
            description: 'Handmade ceramic pitcher with ergonomic design and beautiful earthy glaze, perfect for serving beverages.',
            artisanId: 3,
            createdAt: new Date('2024-01-30').toISOString(),
        },
        {
            name: 'Product 12',
            price: 420,
            image: 'ceramic12.jpg',
            category: 'ceramic-products',
            description: 'Traditional ceramic incense holder with intricate cutwork and delicate glaze finish.',
            artisanId: 7,
            createdAt: new Date('2024-04-22').toISOString(),
        },
        {
            name: 'Product 13',
            price: 750,
            image: 'ceramic13.jpg',
            category: 'ceramic-products',
            description: 'Premium ceramic dinnerware set showcasing masterful pottery skills and elegant design.',
            artisanId: 2,
            createdAt: new Date('2024-02-18').toISOString(),
        },
        {
            name: 'Product 14',
            price: 490,
            image: 'ceramic14.jpg',
            category: 'ceramic-products',
            description: 'Decorative ceramic wall plate with hand-painted village scenes, capturing rural craftsmanship.',
            artisanId: 5,
            createdAt: new Date('2024-03-25').toISOString(),
        },
        {
            name: 'Product 15',
            price: 860,
            image: 'ceramic15.jpg',
            category: 'ceramic-products',
            description: 'Luxury ceramic tea set with gold accents and traditional patterns, perfect for ceremonial tea service.',
            artisanId: 9,
            createdAt: new Date('2024-01-12').toISOString(),
        },
        {
            name: 'Product 16',
            price: 340,
            image: 'ceramic16.jpg',
            category: 'ceramic-products',
            description: 'Simple yet elegant ceramic bowl with organic shape and natural glaze variations.',
            artisanId: 1,
            createdAt: new Date('2024-04-08').toISOString(),
        },
        {
            name: 'Product 17',
            price: 620,
            image: 'ceramic17.jpg',
            category: 'ceramic-products',
            description: 'Handcrafted ceramic candleholder set with textured surface and warm-toned glazing.',
            artisanId: 4,
            createdAt: new Date('2024-02-22').toISOString(),
        },
        {
            name: 'Product 18',
            price: 780,
            image: 'ceramic18.jpg',
            category: 'ceramic-products',
            description: 'Artistic ceramic vase collection featuring abstract designs and contemporary glazing techniques.',
            artisanId: 8,
            createdAt: new Date('2024-03-05').toISOString(),
        },
        {
            name: 'Product 19',
            price: 410,
            image: 'ceramic19.jpg',
            category: 'ceramic-products',
            description: 'Traditional ceramic oil lamp with intricate carvings, preserving ancient pottery traditions.',
            artisanId: 6,
            createdAt: new Date('2024-01-22').toISOString(),
        },
        {
            name: 'Product 20',
            price: 530,
            image: 'ceramic20.jpg',
            category: 'ceramic-products',
            description: 'Handmade ceramic serving bowl with distinctive pattern work and glossy finish.',
            artisanId: 10,
            createdAt: new Date('2024-04-18').toISOString(),
        },
        {
            name: 'Product 21',
            price: 670,
            image: 'ceramic21.jpg',
            category: 'ceramic-products',
            description: 'Decorative ceramic pot with hand-painted tribal motifs and vibrant color combinations.',
            artisanId: 3,
            createdAt: new Date('2024-02-12').toISOString(),
        },
        {
            name: 'Product 22',
            price: 440,
            image: 'ceramic22.jpg',
            category: 'ceramic-products',
            description: 'Rustic ceramic planter with drainage hole and textured exterior, perfect for indoor plants.',
            artisanId: 7,
            createdAt: new Date('2024-03-28').toISOString(),
        },
        {
            name: 'Product 23',
            price: 890,
            image: 'ceramic23.jpg',
            category: 'ceramic-products',
            description: 'Premium ceramic dinner set with gold trim and delicate floral patterns for special occasions.',
            artisanId: 2,
            createdAt: new Date('2024-01-08').toISOString(),
        },
        {
            name: 'Product 24',
            price: 360,
            image: 'ceramic24.jpg',
            category: 'ceramic-products',
            description: 'Simple ceramic cup set with matte finish and comfortable grip, ideal for daily use.',
            artisanId: 5,
            createdAt: new Date('2024-04-15').toISOString(),
        },
        {
            name: 'Product 25',
            price: 740,
            image: 'ceramic25.jpg',
            category: 'ceramic-products',
            description: 'Artisanal ceramic serving tray with raised edges and hand-painted borders.',
            artisanId: 9,
            createdAt: new Date('2024-02-25').toISOString(),
        },
        {
            name: 'Product 26',
            price: 510,
            image: 'ceramic26.jpg',
            category: 'ceramic-products',
            description: 'Handcrafted ceramic mortar and pestle set, combining functionality with traditional design.',
            artisanId: 1,
            createdAt: new Date('2024-03-12').toISOString(),
        },
        {
            name: 'Product 27',
            price: 920,
            image: 'ceramic27.jpg',
            category: 'ceramic-products',
            description: 'Luxury ceramic centerpiece with intricate detailing and museum-quality glazing.',
            artisanId: 4,
            createdAt: new Date('2024-01-28').toISOString(),
        },
        {
            name: 'Product 28',
            price: 380,
            image: 'ceramic28.jpg',
            category: 'ceramic-products',
            description: 'Traditional ceramic soap dish with drainage grooves and natural clay finish.',
            artisanId: 8,
            createdAt: new Date('2024-04-25').toISOString(),
        },
        {
            name: 'Product 29',
            price: 640,
            image: 'ceramic29.jpg',
            category: 'ceramic-products',
            description: 'Decorative ceramic wall hanging with relief work depicting traditional folklore scenes.',
            artisanId: 6,
            createdAt: new Date('2024-02-05').toISOString(),
        },
        {
            name: 'Product 30',
            price: 1000,
            image: 'ceramic30.jpg',
            category: 'ceramic-products',
            description: 'Masterpiece ceramic sculpture with complex layering and exceptional craftsmanship, a collector\'s item.',
            artisanId: 10,
            createdAt: new Date('2024-03-18').toISOString(),
        },

        // POTTERY PRODUCTS (IDs 31-45)
        {
            name: 'Handmade Clay Pot',
            price: 350,
            image: 'pottery1.jpg',
            category: 'pottery',
            description: 'Traditional handmade clay pot crafted using ancient pottery techniques, perfect for cooking and storing.',
            artisanId: 2,
            createdAt: new Date('2024-02-10').toISOString(),
        },
        {
            name: 'Traditional Terracotta Vase',
            price: 420,
            image: 'pottery2.jpg',
            category: 'pottery',
            description: 'Beautiful terracotta vase with natural clay finish, ideal for displaying fresh flowers and greenery.',
            artisanId: 6,
            createdAt: new Date('2024-03-22').toISOString(),
        },
        {
            name: 'Decorative Pottery Bowl',
            price: 380,
            image: 'pottery3.jpg',
            category: 'pottery',
            description: 'Hand-thrown pottery bowl with rustic charm and unique texture, showcasing authentic craftsmanship.',
            artisanId: 9,
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Clay Water Jug',
            price: 290,
            image: 'pottery4.jpg',
            category: 'pottery',
            description: 'Functional clay water jug that keeps water naturally cool, crafted with traditional pottery methods.',
            artisanId: 4,
            createdAt: new Date('2024-04-02').toISOString(),
        },
        {
            name: 'Terracotta Planter Set',
            price: 480,
            image: 'pottery5.jpg',
            category: 'pottery',
            description: 'Set of three terracotta planters in varying sizes, perfect for herbs and small plants.',
            artisanId: 1,
            createdAt: new Date('2024-02-20').toISOString(),
        },
        {
            name: 'Rustic Pottery Mug',
            price: 250,
            image: 'pottery6.jpg',
            category: 'pottery',
            description: 'Handcrafted pottery mug with natural clay texture and comfortable handle, perfect for hot beverages.',
            artisanId: 7,
            createdAt: new Date('2024-03-08').toISOString(),
        },
        {
            name: 'Clay Cooking Pot',
            price: 550,
            image: 'pottery7.jpg',
            category: 'pottery',
            description: 'Traditional clay cooking pot for authentic slow-cooked meals, preserving nutritional value and flavors.',
            artisanId: 3,
            createdAt: new Date('2024-01-25').toISOString(),
        },
        {
            name: 'Terracotta Wind Chimes',
            price: 320,
            image: 'pottery8.jpg',
            category: 'pottery',
            description: 'Handmade terracotta wind chimes producing soothing sounds, combining art with functionality.',
            artisanId: 10,
            createdAt: new Date('2024-04-12').toISOString(),
        },
        {
            name: 'Pottery Serving Plate',
            price: 410,
            image: 'pottery9.jpg',
            category: 'pottery',
            description: 'Large pottery serving plate with natural glaze and earthy tones, perfect for family gatherings.',
            artisanId: 5,
            createdAt: new Date('2024-02-28').toISOString(),
        },
        {
            name: 'Clay Oil Lamp',
            price: 280,
            image: 'pottery10.jpg',
            category: 'pottery',
            description: 'Traditional clay oil lamp (diya) handcrafted for festivals and daily prayers, keeping ancient traditions alive.',
            artisanId: 8,
            createdAt: new Date('2024-03-15').toISOString(),
        },
        {
            name: 'Terracotta Storage Jar',
            price: 460,
            image: 'pottery11.jpg',
            category: 'pottery',
            description: 'Large terracotta storage jar with lid, ideal for keeping grains and pulses fresh naturally.',
            artisanId: 2,
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            name: 'Decorative Pottery Vase',
            price: 520,
            image: 'pottery12.jpg',
            category: 'pottery',
            description: 'Tall decorative pottery vase with hand-carved patterns, a statement piece for any interior.',
            artisanId: 6,
            createdAt: new Date('2024-04-18').toISOString(),
        },
        {
            name: 'Clay Drinking Cup Set',
            price: 340,
            image: 'pottery13.jpg',
            category: 'pottery',
            description: 'Set of six clay drinking cups, providing natural cooling properties and rustic aesthetic.',
            artisanId: 9,
            createdAt: new Date('2024-02-14').toISOString(),
        },
        {
            name: 'Terracotta Wall Art',
            price: 680,
            image: 'pottery14.jpg',
            category: 'pottery',
            description: 'Intricate terracotta wall art depicting traditional scenes, handcrafted by master potters.',
            artisanId: 4,
            createdAt: new Date('2024-03-25').toISOString(),
        },
        {
            name: 'Traditional Pottery Set',
            price: 800,
            image: 'pottery15.jpg',
            category: 'pottery',
            description: 'Complete pottery set including pots, plates, and bowls, showcasing traditional pottery craftsmanship.',
            artisanId: 1,
            createdAt: new Date('2024-01-10').toISOString(),
        },

        // WEAVING PRODUCTS (IDs 46-60)
        {
            name: 'Handwoven Silk Saree',
            price: 1450,
            image: 'weaving1.jpg',
            category: 'weaving',
            description: 'Exquisite handwoven silk saree with traditional motifs, showcasing generations of weaving expertise.',
            artisanId: 3,
            createdAt: new Date('2024-02-08').toISOString(),
        },
        {
            name: 'Traditional Ikat Fabric',
            price: 890,
            image: 'weaving2.jpg',
            category: 'weaving',
            description: 'Authentic Ikat fabric with intricate patterns created through resist-dyeing technique before weaving.',
            artisanId: 7,
            createdAt: new Date('2024-03-20').toISOString(),
        },
        {
            name: 'Pochampally Cotton Dupatta',
            price: 650,
            image: 'weaving3.jpg',
            category: 'weaving',
            description: 'Hand-woven Pochampally cotton dupatta featuring geometric patterns and vibrant color combinations.',
            artisanId: 5,
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'Banarasi Brocade Fabric',
            price: 1280,
            image: 'weaving4.jpg',
            category: 'weaving',
            description: 'Premium Banarasi brocade with golden zari work, perfect for special occasion garments.',
            artisanId: 10,
            createdAt: new Date('2024-04-05').toISOString(),
        },
        {
            name: 'Handloom Cotton Saree',
            price: 720,
            image: 'weaving5.jpg',
            category: 'weaving',
            description: 'Comfortable handloom cotton saree with traditional border and pallu design, ideal for daily wear.',
            artisanId: 2,
            createdAt: new Date('2024-02-25').toISOString(),
        },
        {
            name: 'Kanchipuram Silk Saree',
            price: 1500,
            image: 'weaving6.jpg',
            category: 'weaving',
            description: 'Authentic Kanchipuram silk saree with temple border and contrasting pallu, a bridal favorite.',
            artisanId: 8,
            createdAt: new Date('2024-03-12').toISOString(),
        },
        {
            name: 'Handwoven Khadi Fabric',
            price: 580,
            image: 'weaving7.jpg',
            category: 'weaving',
            description: 'Pure handwoven khadi fabric, breathing life into traditional spinning and weaving heritage.',
            artisanId: 4,
            createdAt: new Date('2024-01-28').toISOString(),
        },
        {
            name: 'Jamdani Muslin Saree',
            price: 1350,
            image: 'weaving8.jpg',
            category: 'weaving',
            description: 'Delicate Jamdani muslin saree with hand-woven motifs, representing centuries-old weaving tradition.',
            artisanId: 9,
            createdAt: new Date('2024-04-15').toISOString(),
        },
        {
            name: 'Chanderi Silk Cotton Dupatta',
            price: 760,
            image: 'weaving9.jpg',
            category: 'weaving',
            description: 'Lightweight Chanderi silk-cotton dupatta with traditional coin motifs and golden zari.',
            artisanId: 1,
            createdAt: new Date('2024-02-18').toISOString(),
        },
        {
            name: 'Patola Silk Saree',
            price: 1480,
            image: 'weaving10.jpg',
            category: 'weaving',
            description: 'Double Ikat Patola saree with intricate geometric patterns, a masterpiece of weaving artistry.',
            artisanId: 6,
            createdAt: new Date('2024-03-28').toISOString(),
        },
        {
            name: 'Maheshwari Cotton Silk Saree',
            price: 850,
            image: 'weaving11.jpg',
            category: 'weaving',
            description: 'Handwoven Maheshwari cotton-silk saree with reversible border and timeless elegance.',
            artisanId: 3,
            createdAt: new Date('2024-01-12').toISOString(),
        },
        {
            name: 'Tussar Silk Stole',
            price: 620,
            image: 'weaving12.jpg',
            category: 'weaving',
            description: 'Natural Tussar silk stole with hand-painted designs, combining weaving with artistic expression.',
            artisanId: 7,
            createdAt: new Date('2024-04-22').toISOString(),
        },
        {
            name: 'Handloom Linen Fabric',
            price: 540,
            image: 'weaving13.jpg',
            category: 'weaving',
            description: 'Pure handloom linen fabric with natural texture and breathable quality, perfect for summer wear.',
            artisanId: 5,
            createdAt: new Date('2024-02-05').toISOString(),
        },
        {
            name: 'Sambalpuri Cotton Saree',
            price: 780,
            image: 'weaving14.jpg',
            category: 'weaving',
            description: 'Traditional Sambalpuri cotton saree with tie-dye patterns and handwoven finish.',
            artisanId: 10,
            createdAt: new Date('2024-03-18').toISOString(),
        },
        {
            name: 'Bhagalpuri Silk Fabric',
            price: 920,
            image: 'weaving15.jpg',
            category: 'weaving',
            description: 'Luxurious Bhagalpuri silk fabric with natural texture and lustrous finish, ideal for elegant drapes.',
            artisanId: 2,
            createdAt: new Date('2024-01-22').toISOString(),
        },

        // WOODEN CRAFTS (IDs 61-70)
        {
            name: 'Carved Wooden Elephant',
            price: 680,
            image: 'wooden1.jpg',
            category: 'wooden-crafts',
            description: 'Intricately carved wooden elephant statue showcasing traditional wood carving techniques and attention to detail.',
            artisanId: 4,
            createdAt: new Date('2024-02-12').toISOString(),
        },
        {
            name: 'Channapatna Toy Set',
            price: 450,
            image: 'wooden2.jpg',
            category: 'wooden-crafts',
            description: 'Colorful Channapatna wooden toy set with natural lacquer finish, safe for children and eco-friendly.',
            artisanId: 8,
            createdAt: new Date('2024-03-25').toISOString(),
        },
        {
            name: 'Sandalwood Box',
            price: 950,
            image: 'wooden3.jpg',
            category: 'wooden-crafts',
            description: 'Handcrafted sandalwood box with carved patterns, emitting natural fragrance and luxury.',
            artisanId: 1,
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Wooden Wall Panel',
            price: 1150,
            image: 'wooden4.jpg',
            category: 'wooden-crafts',
            description: 'Decorative wooden wall panel with relief carving depicting traditional motifs and stories.',
            artisanId: 6,
            createdAt: new Date('2024-04-08').toISOString(),
        },
        {
            name: 'Teak Wood Serving Tray',
            price: 520,
            image: 'wooden5.jpg',
            category: 'wooden-crafts',
            description: 'Sturdy teak wood serving tray with brass handles, combining functionality with artistic craftsmanship.',
            artisanId: 9,
            createdAt: new Date('2024-02-22').toISOString(),
        },
        {
            name: 'Carved Wooden Mirror Frame',
            price: 780,
            image: 'wooden6.jpg',
            category: 'wooden-crafts',
            description: 'Ornate wooden mirror frame with intricate floral carvings, adding elegance to any space.',
            artisanId: 3,
            createdAt: new Date('2024-03-10').toISOString(),
        },
        {
            name: 'Rosewood Jewelry Box',
            price: 850,
            image: 'wooden7.jpg',
            category: 'wooden-crafts',
            description: 'Premium rosewood jewelry box with velvet lining and hand-carved exterior design.',
            artisanId: 7,
            createdAt: new Date('2024-01-28').toISOString(),
        },
        {
            name: 'Wooden Dhokra Art Piece',
            price: 1200,
            image: 'wooden8.jpg',
            category: 'wooden-crafts',
            description: 'Traditional Dhokra art piece on wooden base, blending metal craft with wood carving heritage.',
            artisanId: 5,
            createdAt: new Date('2024-04-18').toISOString(),
        },
        {
            name: 'Hand-painted Wooden Coasters',
            price: 320,
            image: 'wooden9.jpg',
            category: 'wooden-crafts',
            description: 'Set of hand-painted wooden coasters with traditional folk art designs and protective lacquer coating.',
            artisanId: 10,
            createdAt: new Date('2024-02-05').toISOString(),
        },
        {
            name: 'Carved Wooden Chess Set',
            price: 1100,
            image: 'wooden10.jpg',
            category: 'wooden-crafts',
            description: 'Exquisite hand-carved wooden chess set with detailed pieces, combining game with artistic expression.',
            artisanId: 2,
            createdAt: new Date('2024-03-22').toISOString(),
        },

        // JUTE CRAFTS (IDs 71-80)
        {
            name: 'Jute Shopping Bag',
            price: 280,
            image: 'jute1.jpg',
            category: 'jute-crafts',
            description: 'Eco-friendly jute shopping bag with sturdy handles, perfect for sustainable daily use.',
            artisanId: 4,
            createdAt: new Date('2024-02-18').toISOString(),
        },
        {
            name: 'Eco-friendly Jute Mat',
            price: 420,
            image: 'jute2.jpg',
            category: 'jute-crafts',
            description: 'Handwoven jute floor mat with natural texture, durable and biodegradable home accessory.',
            artisanId: 8,
            createdAt: new Date('2024-03-15').toISOString(),
        },
        {
            name: 'Handwoven Jute Basket',
            price: 350,
            image: 'jute3.jpg',
            category: 'jute-crafts',
            description: 'Multi-purpose handwoven jute basket for storage, combining traditional weaving with modern needs.',
            artisanId: 1,
            createdAt: new Date('2024-01-25').toISOString(),
        },
        {
            name: 'Jute Table Runner',
            price: 320,
            image: 'jute4.jpg',
            category: 'jute-crafts',
            description: 'Rustic jute table runner with decorative borders, adding natural elegance to dining spaces.',
            artisanId: 6,
            createdAt: new Date('2024-04-12').toISOString(),
        },
        {
            name: 'Jute Plant Holder',
            price: 260,
            image: 'jute5.jpg',
            category: 'jute-crafts',
            description: 'Decorative jute plant holder with macramé detailing, perfect for indoor plant displays.',
            artisanId: 9,
            createdAt: new Date('2024-02-28').toISOString(),
        },
        {
            name: 'Jute Wall Hanging',
            price: 480,
            image: 'jute6.jpg',
            category: 'jute-crafts',
            description: 'Artistic jute wall hanging with woven patterns and natural fibers, eco-friendly home decor.',
            artisanId: 3,
            createdAt: new Date('2024-03-08').toISOString(),
        },
        {
            name: 'Jute Tote Bag Set',
            price: 540,
            image: 'jute7.jpg',
            category: 'jute-crafts',
            description: 'Set of three jute tote bags in different sizes, sustainable alternative to plastic bags.',
            artisanId: 7,
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'Jute Cushion Cover',
            price: 290,
            image: 'jute8.jpg',
            category: 'jute-crafts',
            description: 'Hand-woven jute cushion cover with cotton lining, adding rustic charm to living spaces.',
            artisanId: 5,
            createdAt: new Date('2024-04-22').toISOString(),
        },
        {
            name: 'Jute Storage Box',
            price: 380,
            image: 'jute9.jpg',
            category: 'jute-crafts',
            description: 'Collapsible jute storage box with lid, combining organization with sustainable materials.',
            artisanId: 10,
            createdAt: new Date('2024-02-10').toISOString(),
        },
        {
            name: 'Jute Lamp Shade',
            price: 600,
            image: 'jute10.jpg',
            category: 'jute-crafts',
            description: 'Handcrafted jute lamp shade with intricate weaving pattern, creating warm ambient lighting.',
            artisanId: 2,
            createdAt: new Date('2024-03-28').toISOString(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully - 80 products created');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});