import { db } from '@/db';
import { videos } from '@/db/schema';

async function main() {
    const sampleVideos = [
        // TUTORIALS (7 videos)
        {
            title: 'How to Make Clay Pottery',
            description: 'Learn the fundamentals of clay pottery making from selecting the right clay to creating your first pot. This comprehensive tutorial covers hand-building techniques, proper clay preparation, and essential tools you need to get started with pottery.',
            videoUrl: 'https://example.com/videos/tutorial1.mp4',
            thumbnail: 'tutorial1.jpg',
            category: 'pottery',
            type: 'tutorial',
            views: 3245,
            artisanId: 3,
            createdAt: new Date('2024-08-15').toISOString(),
        },
        {
            title: 'Weaving Techniques for Beginners',
            description: 'Discover the art of traditional weaving with step-by-step instructions for beginners. This tutorial walks you through basic weaving patterns, loom setup, thread selection, and creating your first woven piece from start to finish.',
            videoUrl: 'https://example.com/videos/tutorial2.mp4',
            thumbnail: 'tutorial2.jpg',
            category: 'weaving',
            type: 'tutorial',
            views: 4567,
            artisanId: 7,
            createdAt: new Date('2024-09-10').toISOString(),
        },
        {
            title: 'Wood Carving Basics',
            description: 'Master the essential wood carving techniques with this beginner-friendly tutorial. Learn about different types of wood, carving tools, safety practices, and basic cuts to create beautiful wooden crafts and decorative pieces.',
            videoUrl: 'https://example.com/videos/tutorial3.mp4',
            thumbnail: 'tutorial3.jpg',
            category: 'wooden-crafts',
            type: 'tutorial',
            views: 2890,
            artisanId: 5,
            createdAt: new Date('2024-10-05').toISOString(),
        },
        {
            title: 'Ceramic Glazing Tutorial',
            description: 'Explore the magical world of ceramic glazing in this detailed tutorial. Learn about different glaze types, application techniques, color combinations, and kiln firing processes to achieve stunning finishes on your ceramic pieces.',
            videoUrl: 'https://example.com/videos/tutorial4.mp4',
            thumbnail: 'tutorial4.jpg',
            category: 'ceramic-products',
            type: 'tutorial',
            views: 1876,
            artisanId: 2,
            createdAt: new Date('2024-11-20').toISOString(),
        },
        {
            title: 'Traditional Jute Weaving',
            description: 'Discover the ancient art of jute weaving with traditional methods passed down through generations. This tutorial covers jute fiber preparation, weaving patterns, and creating sustainable, eco-friendly jute products for everyday use.',
            videoUrl: 'https://example.com/videos/tutorial5.mp4',
            thumbnail: 'tutorial5.jpg',
            category: 'jute-crafts',
            type: 'tutorial',
            views: 3421,
            artisanId: 9,
            createdAt: new Date('2024-07-25').toISOString(),
        },
        {
            title: 'Pottery Wheel Mastery',
            description: 'Take your pottery skills to the next level with advanced wheel throwing techniques. Learn centering, pulling walls, creating even thickness, and shaping various pottery forms including bowls, vases, and cylinders with professional tips.',
            videoUrl: 'https://example.com/videos/tutorial6.mp4',
            thumbnail: 'tutorial6.jpg',
            category: 'pottery',
            type: 'tutorial',
            views: 4923,
            artisanId: 1,
            createdAt: new Date('2024-08-30').toISOString(),
        },
        {
            title: 'Advanced Ceramic Painting',
            description: 'Elevate your ceramic art with advanced painting and decoration techniques. This tutorial covers underglazes, overglazes, detailed brushwork, stenciling, and creating intricate designs that will make your ceramic pieces stand out.',
            videoUrl: 'https://example.com/videos/tutorial7.mp4',
            thumbnail: 'tutorial7.jpg',
            category: 'ceramic-products',
            type: 'tutorial',
            views: 2134,
            artisanId: 4,
            createdAt: new Date('2024-12-10').toISOString(),
        },
        // SHOWCASES (8 videos)
        {
            title: 'Master Potter at Work',
            description: 'Watch a master potter create stunning pottery pieces with decades of experience and skill. This showcase demonstrates the precision, artistry, and dedication required to transform simple clay into beautiful functional art pieces.',
            videoUrl: 'https://example.com/videos/showcase1.mp4',
            thumbnail: 'showcase1.jpg',
            category: 'pottery',
            type: 'showcase',
            views: 6234,
            artisanId: 3,
            createdAt: new Date('2024-09-15').toISOString(),
        },
        {
            title: 'Silk Weaving Showcase',
            description: 'Experience the elegance of traditional silk weaving as skilled artisans create luxurious fabrics. This showcase highlights the intricate patterns, vibrant colors, and meticulous craftsmanship that goes into every woven silk piece.',
            videoUrl: 'https://example.com/videos/showcase2.mp4',
            thumbnail: 'showcase2.jpg',
            category: 'weaving',
            type: 'showcase',
            views: 7845,
            artisanId: 6,
            createdAt: new Date('2024-10-20').toISOString(),
        },
        {
            title: 'Behind the Craft: Ceramic Art',
            description: 'Go behind the scenes to see the complete journey of ceramic art creation. From initial design sketches to final glazed masterpieces, witness the passion and skill that ceramic artists pour into every unique piece.',
            videoUrl: 'https://example.com/videos/showcase3.mp4',
            thumbnail: 'showcase3.jpg',
            category: 'ceramic-products',
            type: 'showcase',
            views: 5432,
            artisanId: 2,
            createdAt: new Date('2024-11-05').toISOString(),
        },
        {
            title: 'Traditional Woodwork Display',
            description: 'Marvel at the beauty of traditional woodworking craftsmanship showcasing intricate carvings and timeless wooden creations. This display features handcrafted furniture, decorative items, and sculptural pieces that celebrate wood as an art form.',
            videoUrl: 'https://example.com/videos/showcase4.mp4',
            thumbnail: 'showcase4.jpg',
            category: 'wooden-crafts',
            type: 'showcase',
            views: 4567,
            artisanId: 8,
            createdAt: new Date('2024-07-18').toISOString(),
        },
        {
            title: 'Jute Craft Excellence',
            description: 'Celebrate the versatility and sustainability of jute crafts through this stunning showcase of innovative designs. See how traditional jute weaving techniques are transformed into modern, eco-friendly products that blend heritage with contemporary style.',
            videoUrl: 'https://example.com/videos/showcase5.mp4',
            thumbnail: 'showcase5.jpg',
            category: 'jute-crafts',
            type: 'showcase',
            views: 3789,
            artisanId: 10,
            createdAt: new Date('2024-08-22').toISOString(),
        },
        {
            title: 'Handloom Heritage',
            description: 'Experience the rich heritage of handloom weaving showcasing traditional patterns and techniques preserved through generations. This collection demonstrates the cultural significance and artistic excellence of handwoven textiles.',
            videoUrl: 'https://example.com/videos/showcase6.mp4',
            thumbnail: 'showcase6.jpg',
            category: 'weaving',
            type: 'showcase',
            views: 6891,
            artisanId: 7,
            createdAt: new Date('2024-09-28').toISOString(),
        },
        {
            title: 'Clay to Creation',
            description: 'Follow the mesmerizing transformation of raw clay into exquisite pottery pieces. This showcase captures the entire creative process, highlighting the skill, patience, and artistic vision required to create functional art from earth.',
            videoUrl: 'https://example.com/videos/showcase7.mp4',
            thumbnail: 'showcase7.jpg',
            category: 'pottery',
            type: 'showcase',
            views: 5678,
            artisanId: 1,
            createdAt: new Date('2024-10-12').toISOString(),
        },
        {
            title: 'Artisan Masterpieces',
            description: 'A curated collection of extraordinary craftsmanship showcasing the finest works from master artisans. This showcase celebrates the diversity of traditional crafts and the dedication of skilled craftspeople who keep these art forms alive.',
            videoUrl: 'https://example.com/videos/showcase8.mp4',
            thumbnail: 'showcase8.jpg',
            category: 'ceramic-products',
            type: 'showcase',
            views: 7234,
            artisanId: 4,
            createdAt: new Date('2024-11-18').toISOString(),
        },
        // COURSES (5 videos)
        {
            title: 'Complete Pottery Course',
            description: 'Enroll in this comprehensive pottery course covering everything from beginner basics to advanced techniques. Learn hand-building, wheel throwing, glazing, and firing through structured lessons. By the end of this course, you will create functional pottery pieces and develop skills for a lifelong craft.',
            videoUrl: 'https://example.com/videos/course1.mp4',
            thumbnail: 'course1.jpg',
            category: 'pottery',
            type: 'course',
            views: 8945,
            artisanId: 3,
            createdAt: new Date('2024-07-10').toISOString(),
        },
        {
            title: 'Master Weaving Certification',
            description: 'Achieve mastery in traditional weaving with this professional certification course. Covers loom types, pattern design, textile finishing, and business aspects of weaving. Includes hands-on projects, expert feedback, and a certificate upon completion to launch your weaving career.',
            videoUrl: 'https://example.com/videos/course2.mp4',
            thumbnail: 'course2.jpg',
            category: 'weaving',
            type: 'course',
            views: 6723,
            artisanId: 6,
            createdAt: new Date('2024-08-05').toISOString(),
        },
        {
            title: 'Ceramic Art Mastery',
            description: 'Transform your passion for ceramics into professional-level artistry with this intensive mastery course. Study advanced forming techniques, surface decoration, glaze chemistry, and kiln management. Create a portfolio of work and gain the confidence to sell your ceramic art.',
            videoUrl: 'https://example.com/videos/course3.mp4',
            thumbnail: 'course3.jpg',
            category: 'ceramic-products',
            type: 'course',
            views: 5834,
            artisanId: 2,
            createdAt: new Date('2024-09-20').toISOString(),
        },
        {
            title: 'Wooden Toy Making Course',
            description: 'Learn the delightful craft of wooden toy making in this family-friendly course. Create safe, beautiful, and educational toys using traditional woodworking techniques. Covers design principles, wood selection, finishing, and safety standards for toy production.',
            videoUrl: 'https://example.com/videos/course4.mp4',
            thumbnail: 'course4.jpg',
            category: 'wooden-crafts',
            type: 'course',
            views: 4567,
            artisanId: 5,
            createdAt: new Date('2024-10-15').toISOString(),
        },
        {
            title: 'Sustainable Jute Crafts',
            description: 'Build a sustainable craft business with this comprehensive jute crafts course. Learn eco-friendly production methods, product design, market trends, and business strategies. Create marketable jute products while contributing to environmental sustainability and supporting traditional crafts.',
            videoUrl: 'https://example.com/videos/course5.mp4',
            thumbnail: 'course5.jpg',
            category: 'jute-crafts',
            type: 'course',
            views: 7123,
            artisanId: 9,
            createdAt: new Date('2024-11-25').toISOString(),
        },
    ];

    await db.insert(videos).values(sampleVideos);
    
    console.log('✅ Videos seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});